-- Generated by Oracle SQL Developer Data Modeler 20.2.0.167.1538
--   at:        2020-09-16 15:25:37 AEST
--   site:      Oracle Database 11g
--   type:      Oracle Database 11g

-- Name : Jason Setiawan
-- ID : 28083148

-- predefined type, no DDL - MDSYS.SDO_GEOMETRY

-- predefined type, no DDL - XMLTYPE
set echo on
SPOOL prop_rental_schema.txt

DROP TABLE damage
DROP TABLE maintenance
DROP TABLE owner
DROP TABLE property
DROP TABLE rent
DROP TABLE tenant
DROP TABLE payment

CREATE TABLE damage (
    damage_no              NUMBER(5, 7) NOT NULL,
    damage_type            VARCHAR2(50),
    damage_date            DATE NOT NULL,
    damage_cost            VARCHAR2(50),
    rent_property_prop_no  NUMBER(7, 5) NOT NULL,
    rent_tent_no           NUMBER(7, 5) NOT NULL
);

ALTER TABLE damage ADD CONSTRAINT damage_pk PRIMARY KEY ( damage_no );

CREATE TABLE maintenance (
    maint_no          NUMBER(7, 5) NOT NULL,
    maint_date        DATE NOT NULL,
    maint_type        VARCHAR2(50),
    maint_cost        VARCHAR2(50 CHAR) NOT NULL,
    property_prop_no  NUMBER(7, 5) NOT NULL
);

ALTER TABLE maintenance ADD CONSTRAINT maintenance_pk PRIMARY KEY ( maint_no );

CREATE TABLE owner (
    owner_no    NUMBER(7, 7) NOT NULL,
    owner_name  VARCHAR2(50 CHAR) NOT NULL
);

ALTER TABLE owner ADD CONSTRAINT owner_pk PRIMARY KEY ( owner_no );

CREATE TABLE payment (
    paym_no                NUMBER(5, 7) NOT NULL,
    paym_date              DATE NOT NULL,
    paym_type              VARCHAR2(50) NOT NULL,
    paym_amount            VARCHAR2(50) NOT NULL,
    rent_property_prop_no  NUMBER(7, 5) NOT NULL,
    rent_tent_no           NUMBER(7, 5) NOT NULL
);

ALTER TABLE payment
    ADD CONSTRAINT chk_pay_type CHECK ( paym_type IN ( 'B',
                                                       'D',
                                                       'R' ) );

ALTER TABLE payment ADD CONSTRAINT payment_pk PRIMARY KEY ( paym_no );

CREATE TABLE property (
    prop_no         NUMBER(7, 5) NOT NULL,
    prop_address    VARCHAR2(50 CHAR) NOT NULL,
    prop_value      VARCHAR2(50 CHAR) NOT NULL,
    owner_owner_no  NUMBER(7, 7) NOT NULL
);

ALTER TABLE property ADD CONSTRAINT property_pk PRIMARY KEY ( prop_no );

CREATE TABLE rent (
    rent_bond         VARCHAR2(50) NOT NULL,
    rent_lease        VARCHAR2(50) NOT NULL,
    property_prop_no  NUMBER(7, 5) NOT NULL,
    tenant_tent_no    NUMBER(7, 5) NOT NULL
);

ALTER TABLE rent ADD CONSTRAINT rent_pk PRIMARY KEY ( property_prop_no,
                                                      tenant_tent_no );

CREATE TABLE tenant (
    tent_no       NUMBER(7, 5) NOT NULL,
    tent_fname    VARCHAR2(50) NOT NULL,
    tent_address  VARCHAR2(50) NOT NULL,
    phone         VARCHAR2(50),
    tent_gname    VARCHAR2(50) NOT NULL
);

ALTER TABLE tenant ADD CONSTRAINT tenant_pk PRIMARY KEY ( tent_no );

ALTER TABLE damage
    ADD CONSTRAINT damage_rent_fk FOREIGN KEY ( rent_property_prop_no,
                                                rent_tent_no )
        REFERENCES rent ( property_prop_no,
                          tenant_tent_no );

ALTER TABLE maintenance
    ADD CONSTRAINT maintenance_property_fk FOREIGN KEY ( property_prop_no )
        REFERENCES property ( prop_no );

ALTER TABLE payment
    ADD CONSTRAINT payment_rent_fk FOREIGN KEY ( rent_property_prop_no,
                                                 rent_tent_no )
        REFERENCES rent ( property_prop_no,
                          tenant_tent_no );

ALTER TABLE property
    ADD CONSTRAINT property_owner_fk FOREIGN KEY ( owner_owner_no )
        REFERENCES owner ( owner_no );

ALTER TABLE rent
    ADD CONSTRAINT rent_property_fk FOREIGN KEY ( property_prop_no )
        REFERENCES property ( prop_no );

ALTER TABLE rent
    ADD CONSTRAINT rent_tenant_fk FOREIGN KEY ( tenant_tent_no )
        REFERENCES tenant ( tent_no );

set echo off
SPOOL off

-- Oracle SQL Developer Data Modeler Summary Report: 
-- 
-- CREATE TABLE                             7
-- CREATE INDEX                             0
-- ALTER TABLE                             14
-- CREATE VIEW                              0
-- ALTER VIEW                               0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                           0
-- ALTER TRIGGER                            0
-- CREATE COLLECTION TYPE                   0
-- CREATE STRUCTURED TYPE                   0
-- CREATE STRUCTURED TYPE BODY              0
-- CREATE CLUSTER                           0
-- CREATE CONTEXT                           0
-- CREATE DATABASE                          0
-- CREATE DIMENSION                         0
-- CREATE DIRECTORY                         0
-- CREATE DISK GROUP                        0
-- CREATE ROLE                              0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE SEQUENCE                          0
-- CREATE MATERIALIZED VIEW                 0
-- CREATE MATERIALIZED VIEW LOG             0
-- CREATE SYNONYM                           0
-- CREATE TABLESPACE                        0
-- CREATE USER                              0
-- 
-- DROP TABLESPACE                          0
-- DROP DATABASE                            0
-- 
-- REDACTION POLICY                         0
-- 
-- ORDS DROP SCHEMA                         0
-- ORDS ENABLE SCHEMA                       0
-- ORDS ENABLE OBJECT                       0
-- 
-- ERRORS                                   0
-- WARNINGS                                 0
